version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: air -c .air.toml
    volumes:
      - .:/go/src/github.com/ryoshindo/go-grpc-tutorial
    ports:
      - 9080:9080
    environment:
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
